[package]
name = "tank_attack"
version = "0.2.0"
authors = []
edition = "2018"

[dependencies]
amethyst_gltf = "0.10.0"

[dependencies.amethyst]
version = "0.15"
features = ["metal"]
# amethyst = {version = "0.10.0", features = ["nightly"]}
